# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SA.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1060, 967)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)



        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.SA = QtWidgets.QWidget()
        self.tabWidget.addTab(self.SA, "fhfh")


        self.groupBox_5 = QtWidgets.QGroupBox(self.SA)
        self.groupBox_5.setGeometry(QtCore.QRect(270, 200, 491, 391))

        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_5)

        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_5)
        self.gridLayout_11.addWidget(self.pushButton_24, 2, 0, 1, 1)

        self.scrollArea_5 = QtWidgets.QScrollArea(self.groupBox_5)
        self.scrollArea_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_5.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea_5.setWidgetResizable(False)
        self.gridLayout_11.addWidget(self.scrollArea_5, 1, 0, 1, 1)

        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        #self.scrollAreaWidgetContents_5.setEnabled(True)
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 451, 490))
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)

        self.gridLayout_12 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_5)
        #self.gridLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)

        self.widget_35 = QtWidgets.QWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_44 = QtWidgets.QGridLayout(self.widget_35)
        self.pushButton_64 = QtWidgets.QPushButton(self.widget_35)
        self.gridLayout_44.addWidget(self.pushButton_64, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_35, 2, 0, 1, 1)

        self.widget_46 = QtWidgets.QWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_56 = QtWidgets.QGridLayout(self.widget_46)
        self.pushButton_75 = QtWidgets.QPushButton(self.widget_46)
        self.gridLayout_56.addWidget(self.pushButton_75, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_46, 3, 0, 1, 1)

        self.widget_47 = QtWidgets.QWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_57 = QtWidgets.QGridLayout(self.widget_47)
        self.pushButton_76 = QtWidgets.QPushButton(self.widget_47)
        self.gridLayout_57.addWidget(self.pushButton_76, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_47, 4, 0, 1, 1)

        self.widget_50 = QtWidgets.QWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_60 = QtWidgets.QGridLayout(self.widget_50)
        self.pushButton_79 = QtWidgets.QPushButton(self.widget_50)
        self.gridLayout_60.addWidget(self.pushButton_79, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_50, 7, 0, 1, 1)

        self.widget_34 = QtWidgets.QWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_43 = QtWidgets.QGridLayout(self.widget_34)
        self.pushButton_63 = QtWidgets.QPushButton(self.widget_34)
        self.gridLayout_43.addWidget(self.pushButton_63, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_34, 1, 0, 1, 1)

        self.widget_48 = QtWidgets.QWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_58 = QtWidgets.QGridLayout(self.widget_48)
        self.pushButton_77 = QtWidgets.QPushButton(self.widget_48)
        self.gridLayout_58.addWidget(self.pushButton_77, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_48, 5, 0, 1, 1)

        self.widget_49 = QtWidgets.QWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_59 = QtWidgets.QGridLayout(self.widget_49)
        self.pushButton_78 = QtWidgets.QPushButton(self.widget_49)
        self.gridLayout_59.addWidget(self.pushButton_78, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_49, 6, 0, 1, 1)

        #self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        #self.gridLayout_11.addWidget(self.scrollArea_5, 1, 0, 1, 1)
        #self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)



        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 451, 490))
    MainWindow.show()
    sys.exit(app.exec_())
