# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogConfirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogConfirmation(object):
    def setupUi(self, Confirmation):
        Confirmation.setObjectName("Confirmation")
        Confirmation.resize(452, 180)
        self.buttonBox = QtWidgets.QDialogButtonBox(Confirmation)
        self.buttonBox.setGeometry(QtCore.QRect(120, 110, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.label = QtWidgets.QLabel(Confirmation)
        self.label.setGeometry(QtCore.QRect(40, 40, 321, 16))
        self.label.setText("Label Texte pour ecrire des trucs")

        self.buttonBox.accepted.connect(Confirmation.accept) # type: ignore
        self.buttonBox.rejected.connect(Confirmation.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Confirmation)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Confirmation = QtWidgets.QDialog()
    ui = Ui_DialogConfirmation()
    ui.setupUi(Confirmation)
    Confirmation.show()
    sys.exit(app.exec_())
