# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainMenu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(546, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 300, 181, 121))
        self.pushButton.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.pushButton.setText("Create New Account")
        self.WhatAccount = QtWidgets.QFrame(self.centralwidget)
        self.WhatAccount.setGeometry(QtCore.QRect(130, 80, 291, 181))
        self.WhatAccount.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WhatAccount.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GoButton = QtWidgets.QPushButton(self.WhatAccount)
        self.GoButton.setGeometry(QtCore.QRect(100, 130, 89, 25))
        self.GoButton.setText("Go")

        self.comboBox = QtWidgets.QComboBox(self.WhatAccount)
        self.comboBox.setGeometry(QtCore.QRect(60, 30, 161, 31))
        self.comboBox.setEditable(False)
        self.comboBox.setCurrentText("")
        self.comboBox.setMaxVisibleItems(5)

        self.pushButton_2 = QtWidgets.QPushButton(self.WhatAccount)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 90, 89, 25))
        self.pushButton_2.setText(("Delete"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 546, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.GoButton, self.pushButton)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainMenu()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
